imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


# app/config/config.yml                                                        
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'  
    firewall_name: main
    user_class: Slackiss\Bundle\SlackwareBundle\Entity\Member
    from_email:
        address:        slackwareim@126.com
        sender_name:    Slackware.im
    resetting:
        token_ttl: 86400
        form:
            type:               fos_user_resetting
            name:               fos_user_resetting_form
            validation_groups:  [ResetPassword, Default]

knp_paginator:
    page_range: 5                   # default page range used in pagination control                 
    default_options:
        page_name: page                # page query parameter name                         
        sort_field_name: sort          # sort field query parameter name                  
        sort_direction_name: direction # sort direction query parameter name               
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements                                                                                
    template:
        pagination: SlackissSlackwareBundle:include:pagination.html.twig


knp_time: ~

liip_imagine:
    filter_sets:
        face_image:
            quality: 75
            filters:
                thumbnail: { size: [175, 260], mode: outbound}
        large_avatar_image:
            quality: 75
            filters:
                thumbnail: { size: [128, 128], mode: outbound }
        avatar_image:
            quality: 75
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
        slacker_image:
            quality: 75
            filters:
                thumbnail: { size: [256, 256], mode: outbound }
        page_image_small:
            quality: 75
            filters:
                thumbnail: { size: [128, 128], mode: outbound }
        page_image:
            quality: 75
            filters:
                relative_resize: { widen: 600 }


knp_gaufrette:
    stream_wrapper: ~
    adapters:
        image_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/images
        avatar_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/avatar
        party_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/party
        desk_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/desk
        discuss_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/discuss
        misc_adapter:
            local:
                directory: %kernel.root_dir%/../web/assets/misc
    filesystems:
        image_fs:
            adapter:    image_adapter
        avatar_fs:
            adapter:    avatar_adapter
        party_fs:
            adapter:    party_adapter
        desk_fs:
            adapter:    desk_adapter
        discuss_fs:
            adapter:    discuss_adapter
        misc_fs:
            adapter:    misc_adapter

vich_uploader:
    db_driver: orm
    twig: true
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        image_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/images
            upload_destination: image_fs
            delete_on_remove: true
            inject_on_load: true
        avatar_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/avatar
            upload_destination: avatar_fs
            delete_on_remove: true
            inject_on_load: true
        party_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/party
            upload_destination: party_fs
            delete_on_remove: true
            inject_on_load: true
        desk_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/desk
            upload_destination: desk_fs
            delete_on_remove: true
            inject_on_load: true
        discuss_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/discuss
            upload_destination: discuss_fs
            delete_on_remove: true
            inject_on_load: true
        misc_image:
            namer: vich_uploader.namer_uniqid
            uri_prefix: /assets/misc
            upload_destination: misc_fs
            delete_on_remove: true
            inject_on_load: true     

hwi_oauth:
    firewall_name: main
    #account_connector: hwi_oauth.user.provider.fosub_bridge
    #registration_form_handler: hwi_oauth.registration.form.handler.fosub_bridge
    #registration_form: fos_user.registration.form
    connect:
        confirmation: true
    resource_owners:
        weibo:
            type:                sina_weibo
            client_id:           %oauth_weibo_key%
            client_secret:       %oauth_weibo_value%
            scope:               "email"
        github:
            type:                github
            client_id:           %oauth_github_key%
            client_secret:       %oauth_github_value%
            scope:               ""
    fosub:
        username_iterations: 120
        properties:
            weibo: weiboId
            github: githubId
