security:
    acl:
        connection: default

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MANAGER:     ROLE_USER
        ROLE_ADMIN:       [ROLE_USER,ROLE_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_USER,ROLE_MANAGER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /post
                use_referer: true
            logout:       true
            anonymous:    true
            remember_me:
                 lifetime: 2592000  # 60*60*24*30

    access_control:
        - { path: ^/login$,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/member/,     role: ROLE_USER}
        - { path: ^/manage/,     role: ROLE_MANAGER}
        - { path: ^/admin/,      role: ROLE_ADMIN}
