security:
    acl:
        connection: default

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_MANAGER:     ROLE_USER
        ROLE_ADMIN:       [ROLE_USER,ROLE_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_USER,ROLE_MANAGER]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
                default_target_path: /post
                use_referer: true
            oauth:
                resource_owners:
                    weibo:          "/login/check-weibo"
                    github:         "/login/check-github"
                login_path:        /login/
                failure_path:      /login/
                oauth_user_provider:
                     service: slackiss_slackware.foshwiuserprovider
            logout:       true
            anonymous:    true
            remember_me:
                 key:      "%secret%"
                 lifetime: 2592000  # 60*60*24*30
                 path:     /
                 domain:   ~

    access_control:
        - { path: ^/login$,      role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register,    role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting,   role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect,     role: IS_AUTHENTICATED_ANONYMOUSLY }     
        - { path: ^/member,      role: ROLE_USER}
        - { path: ^/notice,      role: ROLE_USER}
        - { path: ^/manage/,     role: ROLE_MANAGER}
        - { path: ^/admin/,      role: ROLE_ADMIN}
