<?php

namespace Slackiss\Bundle\SlackwareBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCommentRepository extends EntityRepository
{
}
