<?php

namespace Slackiss\Bundle\KneworkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberRepository extends EntityRepository
{
    public function findByRole($role) {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('u')
           ->from($this->_entityName, 'u')
           ->where('u.roles LIKE :roles')
           ->setParameter('roles', '%' . $role . '%');
        return $qb->getQuery()->getResult();
    }
}
