<?php

namespace Slackiss\Bundle\SlackwareBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCommentRepository extends EntityRepository
{
}
